### ISSUE TITLE
Vite is not ready?

### ISSUE THREAD

**Issue by mdestafadilah** [barelyhuman/preact-islands-diy#1]
any update for ViteJS?

**Comment by barelyhuman** [comment]
In case of vite it'll be a generative codebase and makes the project larger than it needs to be, you are free to try out something like https://github.com/barelyhuman/adex or the helpers from @coxmi https://github.com/coxmi/ssr-tools 

Though understand that it's not as simple as just adding the plugin since there's now 2 sides to be compiled. 

It's not impossible, i'm just tied by bandwidth to be able to focus on these. 

You are free to improve and build up on Adex if you like 😄

**Comment by coxmi** [comment]
I'll also apologise here for the lack of documentation for ssr-tools. There are a couple of bugs I'm working through too, but finding it hard to find the time at the moment due to work constraints.

It'll get there eventually :)
